### ISSUE TITLE
starting from scratch a multilingual mockup 

### ISSUE THREAD

**Issue by zascas** [trevordevore/levurehelper-translate#2]
Hi Trevor,  I write this as an issue because I din't found a better place for a msg to you.

I just started last night my first mockup with your Levure framework.  Thanks so much, you help me to pretend myself a professional on coding.

Do you recommend this translate to add a multilingual structure to  my 1st app? I'm far from the point of have something to publish but I would like to have a good base to work right from the first line.

Summary: Is translate designed for Levure? is enough to have multilingual application from the foundations?

**Comment by trevordevore** [comment]
Hi @zascas! 

This helper is still pretty bare bones, but it does provide the ability to define different translation files in YAML files and specify which language to use. It is a helper that I put in place for an app that isn't localized yet, but which uses the `_t()` function for displaying strings.

What this helper doesn't do is detect which language the operating system is currently using and set the locale accordingly. As it stands you would need to provide a way for the user to change the language from within your app. If you were to start using this helper, and someone were to add the ability to detect the current language, then the helper would start loading the proper locale for you automatically and your existing calls to the `_t()` function would return the proper string.

There is also the question of what to do when the locale is changed. Should a message be broadcast somehow so that controls in your app should be updated? If so, what is the message and who is it broadcast to? With Levure it might make sense to broadcast a message to the current card of all UI stacks in the application that are currently in memory.

It might also be nice to have commands that resize fields to fit the text in them so that when the locale changes you can make sure that label fields fit the text. Another step would be to somehow mark fields that should be updated when the locale changes so that the update can occur automatically.

**Comment by zascas** [comment]
Hi Trevor, 

tanks so much.
